Repository atlasmap/atlasmap, pull requests merged in 2018-03, with the labels that each got.

#325 fix: Avoid undefined nativeElement ref from redrawLinesForMappings if…
  ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.ts
Labels: approved

#328 fix: Avoid materializing the lineMachine object post-check by using i…
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#327 fix: Better error message when Atlasmap Service is not running
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#331 fix: Pull properties/constants up to top of source documents and use …
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
Labels: approved

#333 fix: Disable "Add Field" on JSON/XML doc
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
Labels: approved

#334 fix: Change separator from UI during combine/separate doesn't have an…
  runtime/api/src/main/java/io/atlasmap/spi/AtlasCombineStrategy.java
  runtime/api/src/main/java/io/atlasmap/spi/AtlasSeparateStrategy.java
  runtime/api/src/main/java/io/atlasmap/spi/StringDelimiter.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasCombineStrategy.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasSeparateStrategy.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasCombineStrategyTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasSeparateStrategyTest.java
  runtime/core/src/test/java/io/atlasmap/core/StringDelimiterTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/CombineSeparateChangeDelimiterTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/SourceClass.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/TargetClass.java
  runtime/itests/core/src/test/resources/mappings/issue/combine-separate-change-delimiter-mapping.xml
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved, cat/bug, module/runtime, module/ui

#336 fix: Avoid class loading against primitive types
  runtime/api/src/main/java/io/atlasmap/api/AtlasConversionService.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java
  runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/java_to_java/JavaJavaFieldActionsTest.java
  runtime/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#337 fix: Collection handling of last segment
  runtime/core/src/main/java/io/atlasmap/core/AtlasPath.java
  runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/AtlasMappingBaseTest.java
  runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/java_to_java/JavaJavaCollectionTest.java
  runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/java_to_java/JavaJavaComplexTest.java
  runtime/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-collection-flatprimitive.xml
  runtime/modules/java/core/src/main/java/io/atlasmap/java/core/DocumentJavaFieldReader.java
Labels: approved, cat/bug, module/runtime

#340 fix: Do not prohibit collection when non-collection is already clicke…
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Labels: approved

#339 fix: Fix date/time related runtime code so fields show up correctly in UI
  runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java
  runtime/core/src/main/java/io/atlasmap/converters/CalendarConverter.java
  runtime/core/src/main/java/io/atlasmap/converters/DateConverter.java
  runtime/core/src/main/java/io/atlasmap/converters/DateTimeHelper.java
  runtime/core/src/main/java/io/atlasmap/converters/LocalDateConverter.java
  runtime/core/src/main/java/io/atlasmap/converters/LocalDateTimeConverter.java
  runtime/core/src/main/java/io/atlasmap/converters/LocalTimeConverter.java
  runtime/core/src/main/java/io/atlasmap/converters/ZonedDateTimeConverter.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/core/src/test/java/io/atlasmap/actions/DateFieldActionsTest.java
  runtime/core/src/test/java/io/atlasmap/converters/CalendarConverterTest.java
  runtime/core/src/test/java/io/atlasmap/converters/DateConverterTest.java
  runtime/core/src/test/java/io/atlasmap/converters/LocalDateConverterTest.java
  runtime/core/src/test/java/io/atlasmap/converters/ZonedDateTimeConverterTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java
  runtime/model/src/main/resources/atlas-model-v2.xsd
Labels: approved

#347 fix: Issue an error if the user attempts to create a property with th…
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
Labels: approved

#350 fix tooltip elements from going outside of the page
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
Labels: approved

#355 fix: Add constants support into rt schema and serializer/deserializer…
  runtime/model/src/main/resources/atlas-model-v2.xsd
  ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#356 fix: Prevent multiple mappings to the same target element.
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Labels: approved
