Repository atlasmap/atlasmap, pull requests merged in 2018-02, with the labels that each got.

#283 Tag also minor number when releasing Docker images
  build.sh
Labels: approved

#285 refactor(xml): Make AdditionalSchemas optional
  runtime/modules/xml/model/src/main/resources/atlas-xml-schemaset-model-v2.xsd
Labels: approved

#289 fix: Add tooltips and enlarge icons for repeating mapping/ editing.
  ui/src/app/lib/atlasmap-data-mapper/components/data.mapper.app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#280 fix: filter out redudant converter methods
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
Labels: approved

#296 fix: Correct circular dependency involving the document definition mo…
  ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document.field.detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/field.edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.list.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data.mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping.serializer.ts
Labels: approved

#299 fix: Correct circular dependency involving the document definition mo…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.list.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping.management.service.ts
Labels: approved

#302 chore: Set the Content-Type message header
  camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java
  camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentJavaToJsonTest.java
  camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapMultiNSTest.java
Labels: cat/enhancement, module/camel

#307 chore: Support source/target document shown collapsed at first
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
Labels: cat/blocker, cat/bug, cat/enhancement, module/runtime, target/ga

#308 fix: Remove document-definition.component dependence on line-machine …
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
Labels: approved

#310 fix: Converter not found for sourceType: INTEGER targetType: NUMBER d…
  runtime/api/src/main/java/io/atlasmap/api/AtlasConversionService.java
  runtime/api/src/main/java/io/atlasmap/spi/AtlasConversionInfo.java
  runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java
  runtime/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java
  runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/core/src/test/java/io/atlasmap/core/ConstantModuleTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java
  runtime/core/src/test/java/io/atlasmap/core/PropertyModuleTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/TestHelper.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/Atlasmap233Test.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/CamelAtlasmap14Test.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/SourceClass.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/TargetClass.java
  runtime/itests/core/src/test/resources/mappings/issue/atlasmap-233-mapping.xml
  runtime/itests/core/src/test/resources/mappings/issue/camel-atlasmap-14-mapping.json
  runtime/model/src/main/resources/atlas-model-v2.xsd
  runtime/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java
  runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java
  runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
Labels: approved

#318 fix: wait until the lineMachine instance is created before subscribin…
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
Labels: approved
