Repository atlasmap/atlasmap, pull requests merged in 2018-04, with the labels that each got.

#362 fix: Allow selecting root element for XML Schema document
  ui/karma.conf.js
  ui/package.json
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/tsconfig.spec.json
  ui/test-resources/po-example-schema-result.json
  ui/test-resources/po-example-schema.xsd
  ui/yarn.lock
Labels: approved, status/review-requested

#365 chore: Automate offline inspection to be used for UI unit test
  build.sh
  runtime/atlasmap-maven-plugin/atlasmap-maven-plugin-example.pom
  runtime/atlasmap-maven-plugin/pom.xml
  runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateInspectionsMojo.java
  runtime/atlasmap-maven-plugin/src/test/resources/complex-object-rooted.json
  runtime/atlasmap-maven-plugin/src/test/resources/complex-schema.xsd
  ui/.gitignore
  ui/build.sh
  ui/karma.conf.js
  ui/package.json
  ui/pom.xml
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.spec.ts
  ui/test-resources/po-example-schema-result.json
  ui/test-resources/schema/complex-object-rooted.json
  ui/test-resources/schema/po-example-schema.xsd
Labels: status/review-requested

#370 fix: Fully support compound-selection (ctrl-M1) with separate/combine…
  runtime/core/src/main/java/io/atlasmap/core/BaseModuleValidationService.java
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#373 fix: Correct certain ctrl-m1 select-deselect scenarios
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#378 fix: Correct auto index resequencing for combine/ separate modes.
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#384 Fix for #368: [NumberFieldActions] java.lang.NoSuchMethodException du…
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Labels: approved, status/review-requested

#387 fix: When the user changes a mapping details action it is nether sour…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
Labels: approved, status/review-requested

#390 limit .toolbar class to .DataMapperUI
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
Labels: approved

#391 Fix for #368 (2nd try): [NumberFieldActions] java.lang.NoSuchMethodEx…
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Labels: approved, status/review-requested

#392 fix: Deliver possible values for enum field action parameters
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java
  runtime/model/src/main/resources/atlas-model-v2.xsd
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#396 Fix for #393: Incorrect Transformation options can be selected in UI …
  runtime/core/src/main/java/io/atlasmap/actions/StringSimpleFieldActions.java
  runtime/core/src/test/java/io/atlasmap/actions/StringSimpleFieldActionsTest.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
  runtime/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java
  runtime/model/src/main/resources/atlas-actions-v2.xsd
  runtime/model/src/test/java/io/atlasmap/v2/AtlasModelFactoryTest.java
  runtime/model/src/test/java/io/atlasmap/v2/BaseMarshallerTest.java
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#404 fix: Modify the actions JSON deserializer to support XML generation f…
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
Labels: approved
