Repository atlasmap/atlasmap, pull requests merged in 2018-08, with the labels that each got.

#534 feat: Create GenerateFieldActionsMojo
  docs/src/main/asciidoc/inc/swagger/core/definitions.adoc
  runtime/atlasmap-maven-plugin/atlasmap-maven-plugin-example.pom
  runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/AbstractAtlasMapMojo.java
  runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateFieldActionsMojo.java
  runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateInspectionsMojo.java
  runtime/atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/DummyFieldActions.java
  runtime/atlasmap-maven-plugin/src/test/resources/META-INF/services/io.atlasmap.api.AtlasFieldAction
  runtime/atlasmap-maven-plugin/test.sh
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java
  runtime/model/src/main/resources/atlas-actions-v2.xsd
  runtime/model/src/main/resources/atlas-model-v2.xsd
  runtime/model/src/test/java/io/atlasmap/v2/JsonMarshallerTest.java
  ui/package.json
Labels: cat/enhancement, group/runtime

#545 fix: Constants value is not saved into mapping definition
  camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentTest.java
  camel/src/test/resources/atlasmapping.xml
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#546 fix(modal): update title font, close icon, cancel button, modal fade in/out
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
Labels: approved, status/review-requested
