Repository atlasmap/atlasmap, pull requests merged in 2018-09, with the labels that each got.

#552 feat: Add Split FieldAction
  runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java
  runtime/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java
  runtime/model/src/main/resources/atlas-actions-v2.xsd
Labels: approved

#553 Fix typos
  README.md
  app/README.md
  ui/README.md
Labels: approved

#554 Remove Unnecessary use of fully qualified name
  runtime/core/src/test/java/io/atlasmap/converters/ByteConverterTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/JavaConstructServiceSimpleTest.java
Labels: approved

#564 fix: UI freezes with data preview enabled in table view
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
Labels: approved

#567 fix: Add initial stand-alone and import/export support.
  app/src/app/app.module.ts
  runtime/service/src/main/java/io/atlasmap/service/AtlasService.java
  runtime/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java
  ui/package-lock.json
  ui/package.json
  ui/src/app/atlasmap-navbar.component.html
  ui/src/app/atlasmap-navbar.component.spec.ts
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/example-app.module.ts
  ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts
  ui/src/app/lib/atlasmap-data-mapper/common/data-mapper-util.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/index.html
  ui/yarn.lock
Labels: approved

#575 fix: Correct merge error affecting Constant/Property
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
Labels: approved

#578 fix: XML schema inspection should cache complex type to handle recurs…
  runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java
  runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionFhirTest.java
  runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionRecursiveTest.java
  runtime/modules/xml/core/src/test/resources/inspect/fhir-single.xsd
  runtime/modules/xml/core/src/test/resources/inspect/recursive.xsd
Labels: approved

#583 fix(build): fix demo app build script
  ui/src/app/atlasmap-navbar.component.html
  ui/src/app/atlasmap-navbar.component.ts
Labels: approved, cat/build, group/ui, status/review-requested

#585 Add Fuse early access repository for camel builds.
  pom.xml
Labels: approved

#589 feat(ui): upgrade angular and other required deps
  ui/package-lock.json
  ui/package.json
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/yarn.lock
Labels: approved, group/ui, status/review-requested

#590 Fuse 7.2 pipeline automatic version alignment
  parent/pom.xml
Labels: approved

#594 fix: Handle non-ascii unicode characters in schemas/ instance schemas.
  ui/src/app/atlasmap-navbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#593 chore: remove package-lock.json and have yarn.lock updated with newer…
  ui/package-lock.json
  ui/yarn.lock
Labels: approved

#598 fix: Enable loading spinners on schema/mappings import.
  ui/src/app/atlasmap-navbar.component.html
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved
