Repository atlasmap/atlasmap, pull requests merged in 2018-10, with the labels that each got.

#602 feat: Handle FieldGroup contributed via mapping definition
  docs/src/main/asciidoc/inc/swagger/core/definitions.adoc
  runtime/api/src/main/java/io/atlasmap/spi/AtlasModule.java
  runtime/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java
  runtime/core/src/main/java/io/atlasmap/core/ConstantModule.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/core/src/main/java/io/atlasmap/core/PropertyModule.java
  runtime/core/src/test/java/io/atlasmap/core/BaseDefaultAtlasContextTest.java
  runtime/core/src/test/java/io/atlasmap/core/ConstantModuleTest.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextFactoryTest.java
  runtime/core/src/test/java/io/atlasmap/core/PropertyModuleTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/ConcatenateSplitTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/issue/CollectionComplexTest.java
  runtime/itests/core/src/test/resources/mappings/atlasmapping-concatenate-split.xml
  runtime/itests/core/src/test/resources/mappings/issue/collection-complex-mapping.xml
  runtime/model/src/main/resources/atlas-model-v2.xjb
  runtime/model/src/main/resources/atlas-model-v2.xsd
  runtime/modules/java/core/src/main/java/io/atlasmap/java/core/DocumentJavaFieldWriter.java
  runtime/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/core/BaseDocumentWriterTest.java
  runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java
  runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java
  runtime/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
Labels: approved, status/review-requested

#605 fix: Bump up runtime heap size and increase UI timeout to allow for l…
  runtime/runtime/pom.xml
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#608 feat: Add `ItemAt` and `DayOfMonth` Transformation
  runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java
  runtime/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java
  runtime/core/src/test/java/io/atlasmap/actions/DateFieldActionsTest.java
  runtime/core/src/test/java/io/atlasmap/actions/ObjectFieldActionsTest.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
  runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java
  runtime/model/src/main/resources/atlas-actions-v2.xsd
Labels: approved

#611 fix: Apply transformation for each items in collection if it doesn't …
  parent/pom.xml
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
  runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java
Labels: approved

#616 fix: Class inspection can't inspect nested class
  docs/src/main/asciidoc/inc/swagger/java/definitions.adoc
  runtime/core/src/main/java/io/atlasmap/core/AtlasUtil.java
  runtime/itests/core/src/test/java/io/atlasmap/core/BaseClass.java
  runtime/itests/core/src/test/java/io/atlasmap/core/NestedClassTest.java
  runtime/itests/core/src/test/java/io/atlasmap/core/SourceClass.java
  runtime/itests/core/src/test/java/io/atlasmap/core/TargetClass.java
  runtime/itests/core/src/test/resources/mappings/atlasmapping-nested-class.xml
  runtime/modules/java/core/src/main/java/io/atlasmap/java/core/JavaWriterUtil.java
  runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java
  runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/JavaConstructService.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassValidationUtil.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ComplexClassInspectTest.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/PrimitiveInspectTest.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/PrimitiveValidationUtil.java
  runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestListOrdersTest.java
  runtime/modules/java/model/src/main/resources/atlas-java-model-v2.xsd
  runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java
  runtime/modules/java/test-model/src/main/java/io/atlasmap/java/test/BaseOrder.java
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved

#615 Add Xml To Xml Camel AtlasMap test
  camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentXmlToXmlTest.java
  camel/src/test/resources/atlasmapping-xml-to-xml.json
  camel/src/test/resources/org/apache/camel/component/atlasmap/AtlasMapComponentXmlToXmlTest-context.xml
Labels: approved

#619 fix: when comparing XPaths, namespace uris should be used instead of …
  camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentXmlToXmlDefaultNsTest.java
  runtime/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java
  runtime/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlIOHelper.java
  runtime/modules/xml/core/src/test/java/io/atlasmap/xml/core/XmlFieldReaderTest.java
Labels: approved

#620 fix: Support source-side transformations with no target selected
  runtime/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/test-resources/fieldActions/atlasmap-field-action.json
Labels: approved

#625 fix: UXD requested changes - add new icon to toolsbar - remove import…
  ui/src/app/atlasmap-navbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#626 fix: Correct firefox bug with drag&drop mappings
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
Labels: approved

#627 fix: UI freezes after showing previews in mapping table
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
Labels: approved, status/review-requested

#630 fix: Correct DayOf transformation inclusion
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Labels: approved

#634 fix: Fix issue with export name change in text widget
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#636 fix: Support source side transformation for collections
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#637 fix: Leave combine/separate elements in index order - not alphabetica…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.ts
Labels: approved

#639 fix: Wrong behavior in UI when one source field participates into mul…
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#643 fix: Don't show padding fields or bolts in table view - also correct …
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Labels: approved

#648 fix: Line machine is broken with data preview enabled
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
Labels: approved, status/review-requested

#649 fix: Correct 'Cancel' button on adm file input.
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#646 fix: Fix JSON instance inspection including array handling
  runtime/modules/json/core/src/main/java/io/atlasmap/json/inspect/InstanceInspector.java
  runtime/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonDocumentInspectionServiceTest.java
  runtime/modules/json/core/src/test/resources/inspect/address.json
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts
Labels: approved

#650 fix: "Constant value already exists" error is briefly shown when addi…
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts
Labels: approved, status/review-requested

#654 fix: Ignore null value for COMBINE mode
  runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved, status/review-requested

#656 fix: Correct error diagnostics for missing mapped fields in a mapping…
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
Labels: approved

#660 fix: Concatenate transformation shows up for non-collection source field
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Labels: approved

#659 Upgrade Angular Core to version 7.x
  ui/e2e/app.e2e-spec.ts
  ui/e2e/app.po.ts
  ui/package-lock.json
  ui/package.json
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/yarn.lock
Labels: approved, cat/enhancement, group/ui, status/review-requested
