Repository atlasmap/atlasmap, pull requests merged in 2019-11, with the labels that each got.

#1450 fix: Corrected line machine support to handle added field mappings fr…
  ui/src/app/lib/atlasmap-data-mapper/components/app/line-machine.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1466 feat: Mapper component and the SourceTargetMapper view
  ui-react/packages/atlasmap-standalone/package.json
  ui-react/packages/ui/.storybook/addons.js
  ui-react/packages/ui/.storybook/config.js
  ui-react/packages/ui/.storybook/config.ts
  ui-react/packages/ui/.storybook/presets.js
  ui-react/packages/ui/.storybook/reset.css
  ui-react/packages/ui/.storybook/tsconfig.json
  ui-react/packages/ui/.storybook/webpack.config.js
  ui-react/packages/ui/package.json
  ui-react/packages/ui/src/Box.tsx
  ui-react/packages/ui/src/MappingDetails.tsx
  ui-react/packages/ui/src/canvas/Canvas.tsx
  ui-react/packages/ui/src/canvas/CanvasContext.tsx
  ui-react/packages/ui/src/canvas/CanvasLink.tsx
  ui-react/packages/ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/ui/src/canvas/CanvasObject.tsx
  ui-react/packages/ui/src/canvas/index.ts
  ui-react/packages/ui/src/index.ts
  ui-react/packages/ui/src/mapper/Mapper.tsx
  ui-react/packages/ui/src/mapper/MapperContext.tsx
  ui-react/packages/ui/src/mapper/MapperContextToolbar.tsx
  ui-react/packages/ui/src/mapper/MapperControlBar.tsx
  ui-react/packages/ui/src/mapper/MapperViewToolbar.tsx
  ui-react/packages/ui/src/mapper/index.ts
  ui-react/packages/ui/src/mapper/useMappingLinks.ts
  ui-react/packages/ui/src/models.ts
  ui-react/packages/ui/src/useDebounce.ts
  ui-react/packages/ui/src/useDimensions.ts
  ui-react/packages/ui/src/useMaterializedDrag.ts
  ui-react/packages/ui/src/views/index.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/Box.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/Field.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldElement.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldGroup.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldGroupList.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/Links.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/index.ts
  ui-react/packages/ui/stories/Box.stories.tsx
  ui-react/packages/ui/stories/Mapper.stories.tsx
  ui-react/packages/ui/stories/sampleData.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/Box.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/Field.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/FieldGroup.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/FieldGroupList.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/SourceTargetMapper.stories.tsx
  ui-react/packages/ui/test/Box.test.tsx
  ui-react/packages/ui/tsconfig.json
  ui-react/yarn.lock
Labels: approved

#1475 feat: source-target view with materialized mappings
  ui-react/packages/atlasmap-standalone/src/App.css
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/index.css
  ui-react/packages/atlasmap-standalone/src/index.tsx
  ui-react/packages/ui/src/canvas/Canvas.tsx
  ui-react/packages/ui/src/canvas/CanvasContext.tsx
  ui-react/packages/ui/src/canvas/CanvasLink.tsx
  ui-react/packages/ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/ui/src/canvas/CanvasTransforms.tsx
  ui-react/packages/ui/src/canvas/index.ts
  ui-react/packages/ui/src/canvas/useBoundingCanvasRect.ts
  ui-react/packages/ui/src/common/useDimensions.ts
  ui-react/packages/ui/src/common/useMovable.ts
  ui-react/packages/ui/src/index.ts
  ui-react/packages/ui/src/mapper/Mapper.tsx
  ui-react/packages/ui/src/mapper/MapperContext.tsx
  ui-react/packages/ui/src/mapper/MapperViewToolbar.tsx
  ui-react/packages/ui/src/mapper/MappingDetails.tsx
  ui-react/packages/ui/src/mapper/index.ts
  ui-react/packages/ui/src/models.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/Box.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldElement.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldGroup.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldsBox.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/Links.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/MappingElement.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/MappingsBox.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/SourceTargetMapperContext.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/index.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/useMappingLinks.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/useSourceTargetLinks.ts
  ui-react/packages/ui/stories/Mapper.stories.tsx
  ui-react/packages/ui/stories/sampleData.tsx
  ui-react/packages/ui/stories/utils/fromJava.tsx
  ui-react/packages/ui/stories/utils/fromJson.tsx
  ui-react/packages/ui/stories/utils/fromXML.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/Box.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/Field.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/FieldGroup.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/FieldGroupList.stories.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/SourceTargetMapper.stories.tsx
  ui-react/packages/ui/test/Box.test.tsx
  ui-react/packages/ui/tsconfig.json
Labels: approved

#1480 feat: "materialized" mappings columns, fields d&d
  ui-react/packages/ui/package.json
  ui-react/packages/ui/src/canvas/Canvas.tsx
  ui-react/packages/ui/src/canvas/CanvasLink.tsx
  ui-react/packages/ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/ui/src/mapper/Mapper.tsx
  ui-react/packages/ui/src/mapper/MapperContext.tsx
  ui-react/packages/ui/src/mapper/MapperViewToolbar.tsx
  ui-react/packages/ui/src/mapper/index.ts
  ui-react/packages/ui/src/models.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/Box.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldElement.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldGroup.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/FieldsBox.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/Links.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/MappingElement.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/MappingsBox.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/SourceTargetMapperContext.tsx
  ui-react/packages/ui/src/views/sourcetargetmapper/index.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/useMappingLinks.ts
  ui-react/packages/ui/src/views/sourcetargetmapper/useSourceTargetLinks.ts
  ui-react/packages/ui/stories/Mapper.stories.tsx
  ui-react/packages/ui/stories/sampleData.tsx
  ui-react/packages/ui/stories/views/sourcetargetmapper/SourceTargetMapper.stories.tsx
  ui-react/yarn.lock
Labels: approved

#1482 Checkpoint checkin for #1481 - WIP
  ui-react/packages/ui/package.json
  ui-react/packages/ui/src/mapper/MapperContextToolbar.tsx
  ui-react/packages/ui/src/mapper/MapperUtilsToolbar.ts
  ui-react/packages/ui/src/mapper/index.ts
  ui-react/packages/ui/types/react-file-picker.d.ts
  ui-react/yarn.lock
Labels: pr/wip

#1497 chore: fix wrong gitignore, and add missing files
  .gitignore
  ui-react/packages/atlasmap-provider/example/package.json
  ui-react/packages/atlasmap-provider/package.json
  ui-react/packages/atlasmap-ui/example/package.json
  ui-react/packages/atlasmap-ui/package.json
Labels: approved

#1500 Use newer version of the LTS for Node and NPM
  pom.xml
Labels: approved

#1503 chore(react ui): performance fixes
  ui-react/packages/atlasmap-provider/src/index.ts
  ui-react/packages/atlasmap-provider/src/services/mapping-management.service.ts
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/package.json
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/Box.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/stories/sampleData.tsx
  ui-react/packages/react-use-gesture/.eslintignore
  ui-react/packages/react-use-gesture/.gitignore
  ui-react/packages/react-use-gesture/.npmignore
  ui-react/packages/react-use-gesture/.travis.yml
  ui-react/packages/react-use-gesture/CHANGELOG.md
  ui-react/packages/react-use-gesture/LICENSE
  ui-react/packages/react-use-gesture/README.md
  ui-react/packages/react-use-gesture/package.json
  ui-react/packages/react-use-gesture/src/controllers/GestureController.ts
  ui-react/packages/react-use-gesture/src/defaults.ts
  ui-react/packages/react-use-gesture/src/hooks.ts
  ui-react/packages/react-use-gesture/src/index.ts
  ui-react/packages/react-use-gesture/src/recognizers/CoordinatesRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/DistanceAngleRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/DragRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/HoverRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/MoveRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/PinchRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/PinchWebKitGestureRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/PinchWheelRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/Recognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/ScrollRecognizer.ts
  ui-react/packages/react-use-gesture/src/recognizers/WheelRecognizer.ts
  ui-react/packages/react-use-gesture/src/types.ts
  ui-react/packages/react-use-gesture/src/utils.ts
  ui-react/packages/react-use-gesture/test/Api.test.tsx
  ui-react/packages/react-use-gesture/test/Drag.test.tsx
  ui-react/packages/react-use-gesture/test/Hover.test.tsx
  ui-react/packages/react-use-gesture/test/Move.test.tsx
  ui-react/packages/react-use-gesture/test/MoveHover.test.tsx
  ui-react/packages/react-use-gesture/test/Pinch.test.tsx
  ui-react/packages/react-use-gesture/test/Scroll.test.tsx
  ui-react/packages/react-use-gesture/test/Wheel.test.tsx
  ui-react/packages/react-use-gesture/test/components/Api.tsx
  ui-react/packages/react-use-gesture/test/components/Common.tsx
  ui-react/packages/react-use-gesture/test/components/Interactive.tsx
  ui-react/packages/react-use-gesture/test/components/InteractiveDom.tsx
  ui-react/packages/react-use-gesture/test/components/types.ts
  ui-react/packages/react-use-gesture/tsconfig.json
  ui-react/packages/react-use-gesture/yarn.lock
  ui-react/yarn.lock
Labels: approved

#1504 feat(react ui): load the mapping and connect the mapped fields
  ui-react/packages/atlasmap-provider/src/index.ts
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
Labels: approved

#1509 chore(react ui): optimize the transformation logic between provider and ui
  lib/modules/xml/xsom/XSOM.iml
  ui-react/packages/atlasmap-provider/package.json
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/stories/Mapper.stories.tsx
Labels: approved

#1513 This PR enables the import icon for ADM and JAR.
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/mapper/MapperContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/mapper/MapperUtilsToolbar.ts
  ui-react/packages/atlasmap-ui/src/mapper/index.ts
Labels: approved

#1519 Fixes #1486 Enable support for mapping from nested to non-nested coll…
  lib/itests/core/src/test/java/io/atlasmap/itests/core/NestedCollectionJavaTest.java
  lib/itests/core/src/test/java/io/atlasmap/itests/core/NestedCollectionXmlTest.java
  lib/itests/core/src/test/resources/mappings/atlasmapping-nested-collection-java.json
  lib/itests/core/src/test/resources/mappings/atlasmapping-nested-collection-xml.json
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1517 chore(react ui): fix the rendering performance while dragging
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasContext.tsx
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/MappingList.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/index.ts
  ui-react/packages/atlasmap-ui/stories/Mapper.stories.tsx
Labels: approved

#1521 fix: Remove component method definition out of useAtlasmap.tsx and in…
  ui-react/packages/atlasmap-provider/src/components/toolbar/MapperUtilsToolbar.ts
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
Labels: approved, status/review-requested

#1530 chore(ui-react): some ui tweaks
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-ui/src/canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/models.ts
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldGroupList.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/MappingList.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/index.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts
  ui-react/packages/atlasmap-ui/stories/views/sourcetargetmapper/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/sourcetargetmapper/FieldGroupList.stories.tsx
Labels: approved

#1537 chore(ui-react): heavy refactoring of the canvas view
  ui-react/packages/atlasmap-provider/src/components/toolbar/MapperUtilsToolbar.ts
  ui-react/packages/atlasmap-provider/src/services/file-management.service.ts
  ui-react/packages/atlasmap-provider/src/services/initialization.service.ts
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-ui/src/canvas/Canvas.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasContext.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/common/useDimensions.ts
  ui-react/packages/atlasmap-ui/src/common/useMovable.ts
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/mapper/MapperContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/mapper/index.ts
  ui-react/packages/atlasmap-ui/src/models.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/Box.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/ControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/Field.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/FieldGroupList.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/Links.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/MappingList.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/ViewToolbar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/useMappingLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/useSourceTargetLinks.ts
  ui-react/packages/atlasmap-ui/src/views/index.ts
  ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx
  ui-react/packages/atlasmap-ui/stories/Mapper.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Box.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Field.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroupList.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/sourcetargetmapper/SourceTargetMapper.stories.tsx
  ui-react/packages/atlasmap-ui/test/Box.test.tsx
Labels: approved

#1541 fix: Add glue layer support for export icon.
  ui-react/packages/atlasmap-provider/src/components/toolbar/MapperUtilsToolbar.ts
  ui-react/packages/atlasmap-provider/src/services/file-management.service.ts
  ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/mapper/MapperContextToolbar.tsx
Labels: approved
