Repository atlasmap/atlasmap, pull requests merged in 2019-03, with the labels that each got.

#804 fix: Allow drag&drop unselected field
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
Labels: approved, status/review-requested

#805 fix: the p and g of Mappings is truncated in mapping table view
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
Labels: approved, status/review-requested

#806 fix: Cannot change the settings when clicking on the checkbox
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
Labels: approved, status/review-requested

#807 chore: Set initial focus on a first input element for modal components
  ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/lookup-table.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/template-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/template-edit.component.ts
Labels: approved, status/review-requested

#808 fix: Correct missing mapping lines from large schema document mappings.
  ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved

#810 fix: fix CSS class for constant/property field type pull down
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
Labels: approved, status/review-requested

#813 fix: Cast error on default modal window
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
Labels: approved, status/review-requested

#814 chore: Add unit tests (#812)
  docs/src/main/asciidoc/developer-guide/images/Breakpoint.png
  docs/src/main/asciidoc/developer-guide/images/Chromium.png
  docs/src/main/asciidoc/developer-guide/images/DevTools.png
  docs/src/main/asciidoc/developer-guide/inc/_tips_for_ui_developer.adoc
  ui/karma.conf.js
  ui/package.json
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/error.model.spec.ts
Labels: approved

#816 fix: Correct field detail typeahead popover to correctly list filtere…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#818 fix: Correct AtlasMapping datasource URI for XSD document types and c…
  lib/service/src/main/java/io/atlasmap/service/AtlasService.java
  ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/test-resources/adm/mockdoc.adm
  ui/test-resources/adm/mockdocfhir.adm
Labels: approved, status/review-requested

#820 chore: Add UT for mapping-serializer.service (#812)
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#822 fix: Update user guide for import
  docs/src/main/asciidoc/user-guide/images/ImportJSON1.png
  docs/src/main/asciidoc/user-guide/images/ImportJSON2.png
  docs/src/main/asciidoc/user-guide/images/ImportJSON3.png
  docs/src/main/asciidoc/user-guide/images/ImportJavaClass1.png
  docs/src/main/asciidoc/user-guide/images/ImportJavaClass2.png
  docs/src/main/asciidoc/user-guide/images/ImportJavaClass3.png
  docs/src/main/asciidoc/user-guide/images/ImportJavaClass4.png
  docs/src/main/asciidoc/user-guide/images/ImportJavaClass5.png
  docs/src/main/asciidoc/user-guide/images/ImportXML1.png
  docs/src/main/asciidoc/user-guide/images/ImportXML2.png
  docs/src/main/asciidoc/user-guide/index.adoc
  docs/src/main/asciidoc/user-guide/topics/import_files_to_panel.adoc
  docs/src/main/asciidoc/user-guide/topics/quickstart.adoc
Labels: approved, status/review-requested

#824 fix: Update user guide for export and custom field action.
  docs/src/main/asciidoc/user-guide/images/Export1.png
  docs/src/main/asciidoc/user-guide/images/Export2.png
  docs/src/main/asciidoc/user-guide/images/Trans1.png
  docs/src/main/asciidoc/user-guide/images/Trans2.png
  docs/src/main/asciidoc/user-guide/images/Trans3.png
  docs/src/main/asciidoc/user-guide/images/Trans4.png
  docs/src/main/asciidoc/user-guide/images/Trans5.png
  docs/src/main/asciidoc/user-guide/images/Trans6.png
  docs/src/main/asciidoc/user-guide/images/Trans7.png
  docs/src/main/asciidoc/user-guide/images/Trans8.png
  docs/src/main/asciidoc/user-guide/images/Trans9.png
  docs/src/main/asciidoc/user-guide/index.adoc
  docs/src/main/asciidoc/user-guide/topics/export_files.adoc
  docs/src/main/asciidoc/user-guide/topics/transform_target_data.adoc
Labels: approved

#826 fix: Add 'Reset All' doc and clean up last update.
  docs/src/main/asciidoc/user-guide/images/Reset1.png
  docs/src/main/asciidoc/user-guide/images/Reset2.png
  docs/src/main/asciidoc/user-guide/images/Reset3.png
  docs/src/main/asciidoc/user-guide/images/Reset4.png
  docs/src/main/asciidoc/user-guide/images/Trans4.png
  docs/src/main/asciidoc/user-guide/index.adoc
  docs/src/main/asciidoc/user-guide/topics/reset_files.adoc
  docs/src/main/asciidoc/user-guide/topics/transform_target_data.adoc
Labels: approved, status/review-requested

#836 fix: Transformation is duplicated
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
Labels: approved, backport 1.39.x

#840 ENTESB-10411 Merge prod changes back to dev branch
  ui/pom.xml
  ui/yarn.lock
Labels: approved, status/review-requested
