Repository atlasmap/atlasmap, pull requests merged in 2019-10, with the labels that each got.

#1255 fix: Expand parent fields when mapping is activated (including though…
  ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1256 fix: Java method inspection doesn't detect List as a collection field
  lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java
  lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-add.json
  lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java
  lib/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassValidationUtil.java
  lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/BaseFlatPrimitiveClass.java
  lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/FlatPrimitiveInterface.java
Labels: approved

#1261 Use https instead of http for Maven repositories #1260
  parent/pom.xml
Labels: approved

#1263 user doc: Removes an incorrect . from a command line
  docs/src/main/asciidoc/user-guide/topics/quickstart.adoc
Labels: approved

#1265 fix: Group search result by document in expression box search and fie…
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
Labels: approved

#1267 fix: Establish a mapping mgmt service to execute field searches and c…
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1272 fix: Correct bug in refactoring - make isSource a parameter.
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1273 fix: Allow for validation given no active mapping - as with mapping r…
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1274 fix: Change to pointer icon when hovering over a line - remove embedd…
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.html
Labels: approved

#1278 fix: Move the mapping updated notification up a level to a point wher…
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1279 fix: Ghost field is added when opening existing mapping in Syndesis
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
  ui/test-resources/json/schema/old-action-source.json
  ui/test-resources/json/schema/old-action-target.json
  ui/test-resources/mapping/atlasmapping-old-action.json
Labels: approved, backport atlasmap-1.42.x

#1280 fix: Ghost field is added when opening existing mapping in Syndesis
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved, backport atlasmap-1.42.x

#1294 chore: Update springboot to 1.5.22.RELEASE
  parent/pom.xml
Labels: dependencies

#1295 fix: Ghost field is added when opening existing mapping in Syndesis
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved

#1318 fix: Refactor error-handler service and data-mapper-error component
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/common/to-error-icon-class.pipe.ts
  ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-error.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-error.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/lookup-table.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-error-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/modal-error-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-error-window.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/modal-error-window.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-error-window.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/error.model.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/models/error.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/error-handler.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/error-handler.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/field-action.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/file-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-util.ts
Labels: approved

#1322 fix: UI serializer still uses old action schema
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
Labels: approved

#1347 fix: Refactor all embedded css style info out of html files.
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/namespace-list.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Labels: approved

#1397 fix: Split css file into base, toolbar, document, mapping-detail and …
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-base.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-common.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-document.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-mapping-detail.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-mapping-list.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-toolbar.component.css
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
Labels: approved

#1406 fix: reduce/condense common and merge w/ base css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-base.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-common.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-document.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-mapping-detail.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-mapping-list.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-modal.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-toolbar.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
Labels: approved

#1410 fix: validate/save text in expression action correctly on insertion/d…
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
Labels: approved

#1411 fix: NPE when XML field reader read namespace
  lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/AtlasMap1408Test.java
  lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-mapping.json
  lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-source.xml
  lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-target.json
  lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java
Labels: approved

#1419 fix: UI fails to serialize CustomAction
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
Labels: approved

#1421 chore: add enum/lookuptable mapping to mockdoc.adm
  atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/EnumTestClass.java
  atlasmap-maven-plugin/src/test/java/io/paul/Bicycle.java
  atlasmap-maven-plugin/src/test/java/io/paul/GeoLocation.java
  ui/test-resources/adm/mockdoc.adm
Labels: approved

#1427 fix: Correct lines when panel search reduces fields.
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-document.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
Labels: approved

#1430 fix: Correct show/hide mapping details.
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#1432 upgrade to SpingBoot 1.5.19 and Spring Security 4.2.13
  parent/pom.xml
  standalone/pom.xml
Labels: approved

#1435 feat: Initial setup for the React migration
  ui-react/lerna.json
  ui-react/package.json
  ui-react/packages/atlasmap-standalone/.gitignore
  ui-react/packages/atlasmap-standalone/README.md
  ui-react/packages/atlasmap-standalone/package.json
  ui-react/packages/atlasmap-standalone/public/favicon.ico
  ui-react/packages/atlasmap-standalone/public/index.html
  ui-react/packages/atlasmap-standalone/public/logo192.png
  ui-react/packages/atlasmap-standalone/public/logo512.png
  ui-react/packages/atlasmap-standalone/public/manifest.json
  ui-react/packages/atlasmap-standalone/public/robots.txt
  ui-react/packages/atlasmap-standalone/src/App.css
  ui-react/packages/atlasmap-standalone/src/App.test.tsx
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/index.css
  ui-react/packages/atlasmap-standalone/src/index.tsx
  ui-react/packages/atlasmap-standalone/src/logo.svg
  ui-react/packages/atlasmap-standalone/src/react-app-env.d.ts
  ui-react/packages/atlasmap-standalone/src/serviceWorker.ts
  ui-react/packages/atlasmap-standalone/tsconfig.json
  ui-react/packages/atlasmap-standalone/yarn.lock
  ui-react/packages/ui/.gitignore
  ui-react/packages/ui/.storybook/addons.ts
  ui-react/packages/ui/.storybook/config.ts
  ui-react/packages/ui/.storybook/reset.css
  ui-react/packages/ui/.storybook/webpack.config.js
  ui-react/packages/ui/README.md
  ui-react/packages/ui/build-netlify.sh
  ui-react/packages/ui/example/.gitignore
  ui-react/packages/ui/example/.rescriptsrc.js
  ui-react/packages/ui/example/README.md
  ui-react/packages/ui/example/package.json
  ui-react/packages/ui/example/public/favicon.ico
  ui-react/packages/ui/example/public/index.html
  ui-react/packages/ui/example/public/robots.txt
  ui-react/packages/ui/example/src/App.css
  ui-react/packages/ui/example/src/App.tsx
  ui-react/packages/ui/example/src/index.css
  ui-react/packages/ui/example/src/index.tsx
  ui-react/packages/ui/example/src/react-app-env.d.ts
  ui-react/packages/ui/example/src/serviceWorker.ts
  ui-react/packages/ui/example/tsconfig.json
  ui-react/packages/ui/example/tsconfig.paths.json
  ui-react/packages/ui/example/yarn.lock
  ui-react/packages/ui/netlify.toml
  ui-react/packages/ui/package.json
  ui-react/packages/ui/src/Box.tsx
  ui-react/packages/ui/src/index.ts
  ui-react/packages/ui/stories/Box.stories.tsx
  ui-react/packages/ui/test/Box.test.tsx
  ui-react/packages/ui/test/__mocks__/fileMock.js
  ui-react/packages/ui/test/__mocks__/styleMock.js
  ui-react/packages/ui/test/setup.tsx
  ui-react/packages/ui/tsconfig.json
  ui-react/packages/ui/types/index.d.ts
  ui-react/packages/ui/yarn.lock
  ui-react/yarn.lock
Labels: approved
