Repository atlasmap/atlasmap, pull requests merged in 2019-12, with the labels that each got.

#1549 feat(react-ui): searchable fields
  ui-react/package.json
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/components/toolbar/MapperUtilsToolbar.ts
  ui-react/packages/atlasmap-provider/src/index.ts
  ui-react/packages/atlasmap-provider/src/utils/filter-fields.ts
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/index.tsx
  ui-react/packages/atlasmap-ui/package.json
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/AtlasmapContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/MappingDetails.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/index.ts
  ui-react/packages/atlasmap-ui/src/canvas/Canvas.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasContext.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/canvas/index.ts
  ui-react/packages/atlasmap-ui/src/canvas/useBoundingCanvasRect.ts
  ui-react/packages/atlasmap-ui/src/canvas/useMovable.ts
  ui-react/packages/atlasmap-ui/src/common/Loading.tsx
  ui-react/packages/atlasmap-ui/src/common/index.ts
  ui-react/packages/atlasmap-ui/src/common/useLatestValue.tsx
  ui-react/packages/atlasmap-ui/src/index.ts
  ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx
  ui-react/packages/atlasmap-ui/src/mapper/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewLayoutProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/FieldGroupList.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/MappingList.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Box.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewCanvas.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewToolbar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Field.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBoxHeader.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Links.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useMappingLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useSourceTargetLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/index.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroupList.stories.tsx
  ui-react/yarn.lock
Labels: approved, status/review-requested

#1551 feat(react-ui): move the options from the view toolbar to the view controlbar
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewToolbar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx
Labels: approved

#1552 feat(react-ui): change the canvas BG when in free view mode to better…
  ui-react/packages/atlasmap-ui/src/canvas/Canvas.tsx
Labels: approved

#1557 chore(react-ui): bugfixes and some changes
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/AtlasmapContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/models.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBoxHeader.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroupList.stories.tsx
Labels: approved

#1560 Porting Fixes #1486 Enable support for mapping from nested to non-nes…
  ui-react/packages/atlasmap-provider/src/services/mapping-management.service.ts
  ui-react/packages/atlasmap-provider/test/mapping-management.service.spec.ts
Labels: approved

#1558 feat(react-ui): show the type for a field
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentFooter.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/index.ts
  ui-react/packages/atlasmap-ui/src/canvas/CanvasContext.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasLink.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/canvas/useMovable.ts
  ui-react/packages/atlasmap-ui/src/common/useDimensions.ts
  ui-react/packages/atlasmap-ui/src/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewLayoutProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Links.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useMappingLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useSourceTargetLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/sampleData.tsx
  ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
Labels: approved

#1561 feat(react-ui): confirmation modals
  ui-react/package.json
  ui-react/packages/atlasmap-standalone/public/index.html
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/useConfirmationDialog.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
Labels: approved, status/review-requested

#1564 chore(ui-react): make the d&d logic owned by the atlasmap components
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/index.ts
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DropTarget.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
Labels: approved, status/review-requested

#1565 fix: wire glue layer for document delete
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/components/document/document-util.ts
  ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts
  ui-react/packages/atlasmap-provider/src/services/initialization.service.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
Labels: approved, status/review-requested

#1567 chore(react-ui): DRY the coords calculation logic
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DropTarget.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useLinkable.tsx
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
Labels: approved

#1568 chore(react-ui): clean up a bit storybook stories
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Field.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/index.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Box.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Document.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Field.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBoxHeader.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Labels: approved

#1569 feat(react-ui): automatically expand fields when a mapping is selected
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DropTarget.tsx
  ui-react/packages/atlasmap-ui/src/canvas/CanvasLinks.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewCanvasProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewFieldsProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewOptionsProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewCanvas.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Links.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/index.ts
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Labels: approved, status/review-requested

#1570 feat(react-ui): make fields more visible when a mapping is selected
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
Labels: approved, status/review-requested

#1572 feat(react-ui): UI elements to display mapping previews
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentFieldPreview.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentFieldPreviewResults.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/index.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
Labels: approved, status/review-requested

#1575 feat(react-ui): wire the mapping preview
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/index.ts
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts
  ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
Labels: approved, status/review-requested

#1576 feat(react-ui): quality of life changes
  ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts
  ui-react/packages/atlasmap-ui/stories/sampleData.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Labels: approved

#1525 Issue #930 - Support Multiple Mappings Accessed through Route
  docs/src/main/asciidoc/developer-guide/swagger/core/paths.adoc
  docs/src/main/asciidoc/user-guide/topics/multiple-mapping-definitions-usage.adoc
  lib/model/src/main/java/io/atlasmap/v2/MappingFileType.java
  lib/service/src/main/java/io/atlasmap/service/AtlasService.java
  lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java
  lib/service/src/test/resources/mappings/3/atlasmapping-UI.3.json
  standalone/src/main/java/io/atlasmap/standalone/RoutingConfiguration.java
  ui/src/app/app-routing.module.spec.ts
  ui/src/app/app-routing.module.ts
  ui/src/app/app.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar/toolbar.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/file-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-identifier.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-identifier.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
Labels: approved, status/review-requested

#1578 Add dependency on logback-classic
  parent/pom.xml
Labels: approved, status/review-requested

#1581 fix: UI test failure in mapping-management.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts
Labels: approved

#1584 fix: complete dialog portion of export catalog (ADM)
  ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx
Labels: status/review-requested

#1587 feat(react-ui): improve the add to mapping flow
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/atlasmap/components/DropTarget.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewCanvasProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewLayoutProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewOptionsProvider.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Links.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useMappingLinks.ts
  ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useSourceTargetLinks.ts
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/sampleData.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Document.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Labels: approved, status/review-requested

#1591 fix: add support for old style REST apis (no mapping ID)
  docs/src/main/asciidoc/developer-guide/swagger/core/paths.adoc
  lib/service/src/main/java/io/atlasmap/service/AtlasService.java
  ui-react/packages/atlasmap-provider/src/services/file-management.service.ts
  ui-react/packages/atlasmap-provider/src/services/mapping-management.service.ts
Labels: approved, status/review-requested

#1597 fix: Mappings of an imported ADM catalog can be lost
  lib/service/src/main/java/io/atlasmap/service/AtlasService.java
Labels: approved, status/review-requested

#1598 fix: regression: older .adm file fails to be loaded
  lib/service/src/main/java/io/atlasmap/service/AtlasService.java
Labels: approved

#1596 fix: add placeholder support for export
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx
Labels: status/review-requested

#1605 fix: add challenge dialog to import document if it already exists
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
Labels: approved, status/review-requested

#1614 fix: add support for adding additional mappings for selected dropped …
  ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-provider/src/components/field/field-util.ts
  ui-react/packages/atlasmap-provider/src/services/mapping-management.service.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
Labels: approved, status/review-requested

#1620 I1618
  ui-react/packages/atlasmap-core/src/Atlasmap.tsx
  ui-react/packages/atlasmap-core/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-core/src/components/field/field-util.ts
  ui-react/packages/atlasmap-core/src/models/mapping-definition.model.ts
  ui-react/packages/atlasmap-core/src/services/file-management.service.ts
Labels: approved, status/review-requested

#1622 feat(ui-react): enable the show mapped and hide mapped options
  ui-react/packages/atlasmap-core/src/Atlasmap.tsx
  ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx
  ui-react/packages/atlasmap-core/src/AtlasmapProvider.tsx
  ui-react/packages/atlasmap-core/src/components/field/field-util.ts
  ui-react/packages/atlasmap-core/src/components/toolbar/toolbar-util.ts
  ui-react/packages/atlasmap-core/src/utils/to-ui-models-util.ts
  ui-react/packages/atlasmap-standalone/src/App.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewMappings.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewSource.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewTarget.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentGroup.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DropTarget.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/index.ts
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingDetails.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Box.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/BoxProvider.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewControlBar.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/MappingElement.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/index.ts
  ui-react/packages/atlasmap-ui/src/CanvasView/components/useLinkable.tsx
  ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
  ui-react/packages/atlasmap-ui/stories/sampleData.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/Document.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx
  ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Labels: approved, status/review-requested

#1623 chore(react-ui): performance improvements
  ui-react/packages/atlasmap-standalone/public/index.html
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentFieldPreview.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentFieldPreviewResults.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DragLayer.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx
  ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
  ui-react/packages/atlasmap-ui/src/Canvas/Canvas.tsx
  ui-react/packages/atlasmap-ui/src/Canvas/CanvasContext.tsx
  ui-react/packages/atlasmap-ui/src/Canvas/CanvasLink.tsx
  ui-react/packages/atlasmap-ui/src/Canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/CanvasViewLayoutProvider.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Box.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewCanvas.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/common/useDimensions.ts
Labels: approved, status/review-requested

#1624 chore(react-ui): fix wrong line boundaries detection
  ui-react/packages/atlasmap-ui/src/Canvas/CanvasObject.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Box.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/DocumentProvider.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldElement.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBox.tsx
  ui-react/packages/atlasmap-ui/src/CanvasView/components/index.ts
Labels: approved, status/review-requested
