Repository atlasmap/atlasmap, pull requests merged in 2019-07, with the labels that each got.

#1071 fix: [UI] Split file handling into file-management.service
  ui/src/app/atlasmap-navbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/file-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1072 fix: Add d&d support for in-line field insertion for conditional expr…
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#1075 Partial fix for issue 1073 - needed to track down a custom field acti…
  atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/Bicycle.java
  atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/GeoLocation.java
  atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/PaulsFieldActions.java
  atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/PaulsFieldActionsModel.java
  atlasmap-maven-plugin/src/test/resources/META-INF/services/io.atlasmap.spi.AtlasFieldAction
  atlasmap-maven-plugin/src/test/resources/META-INF/services/io.atlasmap.v2.Action
Labels: approved

#1080 fix: Already mapped target check should look at docId and path
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Labels: approved

#1074 fix: [UI] Don't show multiplicity transformations where not eligible
  ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts
Labels: approved, status/review-requested

#1081 fix: Remove NoneField usage for compound selection
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/input-mapping.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/input-mapping.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-pair-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-pair-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#1085 fix: Mapping details search box pulldown shows only leaf names
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
Labels: approved

#1091 feat: Support topmost collection Java object for standalone
  lib/modules/java/service/src/main/java/io/atlasmap/java/service/JavaService.java
  ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts
  ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved

#1094 fix: Add check icon for directed save at the end of input widget for …
  ui/src/app/lib/atlasmap-data-mapper/common/data-mapper-util.ts
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
  ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
Labels: approved

#1104 fix: Make transformation argument input and expression input mappings…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.ts
Labels: approved

#1106 fix: Remove trailing padding fields.
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Labels: approved

#1107 fix: Correct modal reset to not automatically clear errors.
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Labels: approved

#1112 fix: [UI] Clean up transition&index handling
  ui/pom.xml
  ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
  ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#1114 fix: If no documents exist on the runtime then don't bother loading f…
  ui/src/app/lib/atlasmap-data-mapper/services/field-action.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Labels: approved

#1115 fix: [UI] transition to many-to-one/one-to-many mapping for collectio…
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#1116 Correct custom action name ref and init default action refs.
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/field-action.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
  ui/test-resources/adm/mockdoc.adm
  ui/test-resources/xml/schema/fhir-rafal-170.xsd
Labels: approved

#1118 fix: Correct sources/targets fields to update their type info dynamic…
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
  ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1119 user doc: New doc for applying conditions to mappings
  docs/src/main/asciidoc/user-guide/images/add-condition-to-mapping.png
  docs/src/main/asciidoc/user-guide/images/first-conditional-mapping-expression.png
  docs/src/main/asciidoc/user-guide/images/first-conditional-mapping.png
  docs/src/main/asciidoc/user-guide/images/second-conditional-mapping-expression.png
  docs/src/main/asciidoc/user-guide/images/second-conditional-mapping.png
  docs/src/main/asciidoc/user-guide/index.adoc
  docs/src/main/asciidoc/user-guide/topics/applying_conditions_to_mappings.adoc
  docs/src/main/asciidoc/user-guide/topics/separate_one_source_field_into_multiple_target_fields.adoc
Labels: approved, status/review-requested

#1134 fix: Correct processing mapped fields from the catalog.
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
  ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
  ui/test-resources/adm/mockdocfhir.adm
Labels: approved

#1135 fix: Add PaulsFieldActions and Bicycle for custom field action test.
  ui/test-resources/adm/mockdoc.adm
Labels: approved

#1137 fix: Correct document removal to not fail on padding fields and to de…
  ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
  ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
Labels: approved

#1138 chore: Added basics to user-doc
  docs/src/main/asciidoc/user-guide/index.adoc
  docs/src/main/asciidoc/user-guide/topics/basics.adoc
Labels: status/review-requested

#1140 fix: Optimize the space usage in the mapping detail panel.
  ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
  ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html
Labels: approved

#1147 fix: Backport fix to removeMapping in the mapping-management service,
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1149 fix: Backport fixes in mapping management service and mapping seriali…
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved

#1152 fix: [UI] undefined error when clicking a field
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Labels: approved

#1150 fix: [UI] Remove mappingDefinition arg from deserializeMappingService…
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.spec.ts
  ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Labels: approved
